import React, { useState } from 'react';
import { motion } from 'framer-motion';
import SEO from '@/components/SEO';
import Navbar from '@/components/landing/Navbar';
import FooterSection from '@/components/landing/FooterSection';
import NewsletterSignup from '@/components/ui/NewsletterSignup';
import { FileText, Download, Search, Shield, Table, Lock, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import jsPDF from 'jspdf';
import { useToast } from '@/components/ui/use-toast';
import { whitepaperContent } from '@/lib/whitepaperContent';

const generatePDF = (data) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(10, 10, 10);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(191, 167, 106);
    doc.setFontSize(24);
    doc.text("POWALYZE", 20, 25);
    
    // Title
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(18);
    doc.text(data.title.toUpperCase(), 20, 60);
    
    // Content (Split logic for multi-page)
    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    
    const splitText = doc.splitTextToSize(data.content, 170);
    let y = 80;
    
    splitText.forEach(line => {
      if (y > 270) {
        doc.addPage();
        y = 30;
      }
      doc.text(line, 20, y);
      y += 7;
    });
    
    // Footer on last page
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Powalyze.ch - Excellence Opérationnelle", 20, 280);
    
    doc.save(`${data.title.replace(/\s+/g, '_')}.pdf`);
};

const ResourceCard = ({ title, type, description, date, author, category, contentKey }) => {
  const { toast } = useToast();

  const handleDownload = () => {
    try {
        const content = whitepaperContent[contentKey];
        if (!content) throw new Error("Content not found");
        
        generatePDF(content);
        toast({
            title: "Téléchargement terminé",
            description: "Votre fichier PDF a été généré avec succès.",
            variant: "success"
        });
    } catch (e) {
        toast({
            title: "Erreur",
            description: "Impossible de générer le fichier.",
            variant: "destructive"
        });
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="group bg-[#0A0A0A] border border-white/5 hover:border-[#BFA76A]/30 rounded-xl overflow-hidden transition-all duration-300 flex flex-col h-full"
    >
      <div className="h-48 overflow-hidden relative bg-[#111] flex items-center justify-center">
        {category === 'guide' && <Shield size={48} className="text-white/20 group-hover:text-[#BFA76A] transition-colors" />}
        {category === 'template' && <Table size={48} className="text-white/20 group-hover:text-[#BFA76A] transition-colors" />}
        {category === 'whitepaper' && <FileText size={48} className="text-white/20 group-hover:text-[#BFA76A] transition-colors" />}
        
        <div className="absolute top-4 left-4 z-20">
          <span className="bg-[#BFA76A]/10 text-[#BFA76A] px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider">
            {type}
          </span>
        </div>
      </div>
      
      <div className="p-6 flex flex-col flex-grow">
        <div className="flex justify-between items-start mb-4">
          <span className="text-xs text-[#BFA76A] uppercase tracking-widest font-medium">{category}</span>
          <span className="text-xs text-gray-500">{date}</span>
        </div>
        
        <h3 className="text-xl font-display text-white mb-3 group-hover:text-[#BFA76A] transition-colors">{title}</h3>
        <p className="text-sm text-gray-400 font-light leading-relaxed mb-6 flex-grow">{description}</p>
        
        <div className="mt-auto pt-6 border-t border-white/5 flex items-center justify-between">
          <span className="text-xs text-gray-500">{author}</span>
          <Button 
            onClick={handleDownload}
            variant="ghost" 
            className="text-white hover:text-[#BFA76A] hover:bg-white/5 p-0 h-auto flex gap-2"
          >
            <Download size={16} />
            <span className="text-xs font-bold uppercase">Télécharger</span>
          </Button>
        </div>
      </div>
    </motion.div>
  );
};

const Resources = () => {
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');

  const resources = [
    {
      id: 1,
      title: "PMO Strategy Guide",
      type: "PDF",
      category: "whitepaper",
      description: "Guide complet de 50+ pages sur les meilleures pratiques PMO, modèles et études de cas.",
      date: "Oct 2025",
      author: "Fabrice Fays",
      contentKey: "pmo"
    },
    {
      id: 2,
      title: "Governance Framework",
      type: "PDF",
      category: "guide",
      description: "Cadre de gouvernance IT, conformité ISO et procédures d'audit.",
      date: "Sep 2025",
      author: "Équipe Risque",
      contentKey: "governance"
    },
    {
      id: 3,
      title: "Data Analytics Playbook",
      type: "PDF",
      category: "whitepaper",
      description: "Stratégie de données, définition des KPIs et roadmap d'implémentation.",
      date: "Nov 2025",
      author: "Tech Lead",
      contentKey: "data"
    },
    {
      id: 4,
      title: "Digital Transformation",
      type: "PDF",
      category: "whitepaper",
      description: "Feuille de route pour la transformation numérique et la gestion du changement.",
      date: "Août 2025",
      author: "Strategy Team",
      contentKey: "digital"
    },
    {
      id: 5,
      title: "Executive Summary Templates",
      type: "PDF",
      category: "template",
      description: "Modèles prêts à l'emploi pour vos rapports de direction.",
      date: "Juil 2025",
      author: "Comex Team",
      contentKey: "executive"
    },
    {
      id: 6,
      title: "Risk Management Handbook",
      type: "PDF",
      category: "guide",
      description: "Manuel de gestion des risques, matrices et plans de mitigation.",
      date: "Oct 2025",
      author: "Risk Officer",
      contentKey: "risk"
    }
  ];

  const filteredResources = resources.filter(r => {
    const matchesFilter = filter === 'all' || r.category === filter;
    const matchesSearch = r.title.toLowerCase().includes(search.toLowerCase()) || r.description.toLowerCase().includes(search.toLowerCase());
    return matchesFilter && matchesSearch;
  });

  return (
    <div className="bg-[#050505] min-h-screen">
      <SEO 
        title="Ressources & Insights - Powalyze"
        description="Accédez à nos livres blancs, modèles et guides experts pour optimiser votre pilotage stratégique."
      />
      <Navbar />

      <div className="pt-32 pb-20 container mx-auto px-6">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center max-w-3xl mx-auto mb-16"
        >
          <span className="text-[#BFA76A] text-sm font-bold uppercase tracking-[0.2em] mb-4 block">
            Centre de Connaissances
          </span>
          <h1 className="text-4xl md:text-6xl font-display text-white mb-6">
            Ressources & <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#BFA76A] to-[#D4AF37]">Outils Stratégiques</span>
          </h1>
          <p className="text-gray-400 text-lg font-light leading-relaxed">
            Une bibliothèque exclusive de contenus premium conçus pour les décideurs.
          </p>
        </motion.div>

        {/* Filters */}
        <div className="flex flex-col md:flex-row justify-between items-center gap-6 mb-12 border-b border-white/10 pb-8">
          <div className="flex gap-2">
            {['all', 'whitepaper', 'template', 'guide'].map((cat) => (
              <button
                key={cat}
                onClick={() => setFilter(cat)}
                className={`px-4 py-2 rounded-full text-sm font-medium transition-all capitalize ${
                  filter === cat ? 'bg-[#BFA76A] text-black' : 'bg-white/5 text-gray-400'
                }`}
              >
                {cat}
              </button>
            ))}
          </div>

          <div className="relative w-full md:w-64">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500" size={16} />
            <Input 
              type="text" 
              placeholder="Rechercher..." 
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-10 bg-white/5 border-white/10 text-white focus:border-[#BFA76A]"
            />
          </div>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-24">
          {filteredResources.map((resource) => (
            <ResourceCard key={resource.id} {...resource} />
          ))}
        </div>
      </div>

      <NewsletterSignup />
      <FooterSection />
    </div>
  );
};

export default Resources;