
import React from 'react';
import { motion } from 'framer-motion';
import { Target, TrendingUp, Eye, Zap, CheckCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/components/ui/use-toast';

const SolutionPMO = ({ language }) => {
  const { toast } = useToast();
  
  const handleCTA = () => {
    toast({ title: "Redirecting to Demo Request..." });
  };

  const content = {
    fr: {
      hero: {
        title: "PMO Stratégique",
        subtitle: "Transformez votre PMO en moteur de création de valeur.",
        desc: "Alignement stratégique, exécution fluide, visibilité totale. Décisions plus rapides, meilleure allocation budgétaire, risque réduit.",
        cta: "Découvrir la solution"
      },
      benefits: [
        { title: "Alignement Stratégique", desc: "Assurez que chaque projet sert directement les objectifs de l'entreprise.", icon: Target },
        { title: "Exécution Fluide", desc: "Supprimez les goulots d'étranglement et accélérez le time-to-market.", icon: Zap },
        { title: "Visibilité Temps Réel", desc: "Plus de rapports Excel obsolètes. Des données live pour décider maintenant.", icon: Eye },
        { title: "ROI Mesurable", desc: "Suivez la valeur générée par chaque franc investi.", icon: TrendingUp }
      ]
    },
    en: {
      hero: {
        title: "Strategic PMO",
        subtitle: "Transform your PMO into a value creation engine.",
        desc: "Strategic alignment, seamless execution, total visibility. Faster decisions, better budget allocation, reduced risk.",
        cta: "Discover the Solution"
      },
      benefits: [
        { title: "Strategic Alignment", desc: "Ensure every project directly serves company objectives.", icon: Target },
        { title: "Seamless Execution", desc: "Remove bottlenecks and accelerate time-to-market.", icon: Zap },
        { title: "Real-Time Visibility", desc: "No more obsolete Excel reports. Live data for instant decisions.", icon: Eye },
        { title: "Measurable ROI", desc: "Track the value generated by every franc invested.", icon: TrendingUp }
      ]
    }
  };

  const t = content[language];

  return (
    <div className="bg-[#0F0F0F] min-h-screen">
      {/* Hero */}
      <section className="relative pt-32 pb-20 px-4 overflow-hidden">
        <div className="absolute top-0 right-0 w-1/2 h-full bg-[#1E3A8A]/10 blur-3xl rounded-full" />
        <div className="container mx-auto max-w-6xl relative z-10 text-center">
          <motion.h1 
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
            className="text-5xl md:text-7xl font-bold text-white mb-6 font-[Cinzel]"
          >
            {t.hero.title}
          </motion.h1>
          <motion.p 
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
            className="text-2xl text-[#D4A574] font-light mb-8"
          >
            {t.hero.subtitle}
          </motion.p>
          <motion.p 
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
            className="text-xl text-slate-400 max-w-3xl mx-auto mb-10 leading-relaxed"
          >
            {t.hero.desc}
          </motion.p>
          <Button onClick={handleCTA} size="lg" className="bg-[#D4A574] hover:bg-[#B58554] text-black font-bold text-lg px-8 py-6 rounded-full">
            {t.hero.cta}
          </Button>
        </div>
      </section>

      {/* Benefits Grid */}
      <section className="py-20 px-4 bg-[#151515]">
        <div className="container mx-auto max-w-6xl">
          <div className="grid md:grid-cols-2 gap-8">
            {t.benefits.map((b, i) => (
              <motion.div 
                key={i} 
                initial={{ opacity: 0, y: 20 }} 
                whileInView={{ opacity: 1, y: 0 }} 
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="p-8 rounded-2xl bg-[#0F0F0F] border border-slate-800 hover:border-[#D4A574]/50 transition-colors group"
              >
                <b.icon className="w-10 h-10 text-[#D4A574] mb-4 group-hover:scale-110 transition-transform" />
                <h3 className="text-2xl font-bold text-white mb-2">{b.title}</h3>
                <p className="text-slate-400">{b.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Case Study Snippet */}
      <section className="py-20 px-4">
        <div className="container mx-auto max-w-4xl bg-gradient-to-r from-[#1E3A8A]/20 to-[#0F0F0F] border border-[#1E3A8A]/40 rounded-3xl p-10">
          <div className="flex flex-col md:flex-row gap-8 items-center">
            <div className="flex-1">
               <h3 className="text-[#D4A574] uppercase tracking-widest font-bold text-sm mb-2">Success Story</h3>
               <h2 className="text-3xl font-bold text-white mb-4">Fusion Bancaire Suisse</h2>
               <p className="text-slate-300 mb-6">"Powalyze nous a permis de piloter 120M€ d'investissements avec une clarté absolue. Nous avons réduit nos coûts IT de 22% en 18 mois."</p>
               <div className="flex items-center gap-4">
                 <div className="flex flex-col">
                   <span className="text-white font-bold">Jean-Marc D.</span>
                   <span className="text-slate-500 text-sm">CIO, Private Bank</span>
                 </div>
               </div>
            </div>
            <div className="w-full md:w-1/3 bg-[#0F0F0F] p-6 rounded-xl border border-slate-800 text-center">
               <div className="text-4xl font-bold text-[#D4A574] mb-1">22%</div>
               <div className="text-sm text-slate-500">Cost Reduction</div>
               <div className="my-4 h-px bg-slate-800 w-full" />
               <div className="text-4xl font-bold text-white mb-1">3x</div>
               <div className="text-sm text-slate-500">Faster Decisions</div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default SolutionPMO;
